package org.pascallexer;

public enum TokenType {
    // Operators
    PLUS, MINUS, ASTERISK, SLASH,
    EQUAL, LESS, GREATER,
    NOT_EQUAL, LESSEQ, GREATEQ, BECOMES,

    // Punctuation
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, PERIOD, SEMICOLON, COLON, DOUBLEPERIOD,

    // Literals
    IDENTIFIER, STRING_LITERAL, CHAR_LITERAL, INTEGER_LITERAL, REAL_LITERAL,
    // Boolean literals
    TRUE, FALSE,

    // Types
    INTEGER, REAL, BOOLEAN, STRING, CHAR, BYTE, SMALLINT, LONGINT,

    // Keywords
    AND, ARRAY, BEGIN, CASE, CONST, DIV, DO,
    DOWNTO, ELSE, END, FILE, FOR, FUNCTION, GOTO,
    IF, IN, LABEL, MOD, NIL, NOT, OF, OR,
    PACKED, PROCEDURE, PROGRAM, RECORD,
    REPEAT, SET, THEN, TO, TYPE,
    UNTIL, VAR, WHILE, WITH,

    EOF
}
